sudo: required
language: bash
env:
- DOKKU_VERSION=master
before_install: make setup
script: make test
notifications:
  slack:
    secure: PiqAzlLhGENdra4zN1zhj3XdrRHtRaKd3LvMmBJJPeDPPJZSue/j8uAscs0TZ+ljR2koY+40urHzQWr59gdkR9NeMo4MY+nwRyN6hCdgaCytx6cGMMSZBFZ38lk2XRuerw17keldZCN5uE5BZijOf2JZdbaWxPmWprwBPXZasqCun9L8AGf5mLC6iv6TKXyB7mmlmb3k6SAeglgnMkq/wUCBvNRcVdIy/xotCrDZZTtVJQ9Tg3Xg6TFtCogtrFn5Id59yHNongEQ4UpSzf09pnnuRQFIIqjnFOW29aNZrh64J8fUTZTSy1CTVsgj2GuN9FtwlSxTTCgTV7TC1PQPvLiwNTJQfbEmw26UOBTNiY703FnDLtHUqDA3/El+z5CN9Eg1ZDUojec105Af2h330HppLjTXt+NqiZRWf3NJcCdqNihVWvyVegQkU6Y0aI38WK0CxIU1bsG0uB3OP2EOH81xedx80H1kQDe2EQi1XbK/6R+EQFoUEUgEvIHxCRxVJq9fsk8necBzAW2Fs5D4ktvdOBTLdbJkFkEy8eE8SqtBRTvxnBJXQlR1nH3s8wzTvYR30y3OCTEylt0+BUu4SRWjQUvG/zxAb0udHghhqOTroLCNn9ezhzX+kA5Sfs2ortbTi44cB/9sK2Uz8V4xcdf0RD7rQayQdL5H2FNUPrk=
